### ISSUE TITLE
Blog Entry based placeholder

### ISSUE THREAD

**Issue by retailify** [nephila/djangocms-blog#127]
Hi Yakky, 
it would be cool, to set the placeholder functionality for each item in the blog dynamically. 

Now it's an all or nothing thing. If I decide to use BLOG_USE_PLACEHOLDER = False I've no chance to add a PDF File, images or other content. In most of the cases the customer does'nt need more than BLOG_USE_PLACEHOLDER = False functionality. But if he needs it...

Therefore a dynamic change of the behaviour for each blog entry would be really cool. 

Regards
Thomas

**Comment by yakky** [comment]
Actually the label ``BLOG_USE_PLACEHOLDER`` is a bit misleading. The only ``hard`` action it does is to hide / show the ``post_text`` field in the admin. The other action is a check in templates, but it's easy to override it.
Instead of :

    {% if use_placeholder %}
        <div class="blog-content">{% render_placeholder post.content %}</div>
    {% else %}
        <div class="blog-content">{% render_model post "post_text" "post_text" %}</div>
    {% endif %}

You can write:

    {% if post.post_text %}
        <div class="blog-content">{% render_model post "post_text" "post_text" %}</div>
    {% else %}
        <div class="blog-content">{% render_placeholder post.content %}</div>
    {% endif %}

By using this, if the ``post_text`` field is empty, the placeholder is used; as soon as ``post_text`` is populated the placeholder goes away.

Or just use 

        <div class="blog-content">{% render_model post "post_text" "post_text" %}</div>
        <div class="blog-content">{% render_placeholder post.content %}</div>

And then you have both fields available, for different scopes

**Comment by retailify** [comment]
Ok!
I'll change the admin with a simple checkbox / jquery function to show/hide the text field. I think there is also a change in the cms_plugin model needed. The extra model field can also be used to change the template behaviour. 
What do you think?

**Comment by yakky** [comment]
Why a change in the cms_plugin model should be needed?
I am not a big fan of adding boolean flags when it's possible to use model data

**Comment by retailify** [comment]
you are right - it's possible to show/hide the text field like the other groups (info, imaggine, seo)

**Comment by yakky** [comment]
Closing this as non issue
