### ISSUE TITLE
Custom model

### ISSUE THREAD

**Issue by vivekkalyan** [nephila/djangocms-blog#268]
How do i go about integrating a custom model into the blog? For example a poll app that I want to be created by content managers (but with the same features of a post that the blog provides)

**Comment by yakky** [comment]
There is currently no plan to provide an API to swap the post model, but you can achieve the same goal using an external model with a onetoonefield to the post model and overriding the post admin to handle the onetoone as a admin inline

**Comment by vivekkalyan** [comment]
am i doing it correctly?

```
#models.py
from djangocms_blog.models import Post

class MyModel(models.Model)
    post =  OneToOneField(Post, on_delete=models.CASCADE, primary_key=True)

#admin.py
from djangocms_blog.admin import PostAdmin

class MyModelAdmin(PostAdmin):
    model = MyModel

admin.site.register(MyModel, MyModelAdmin)
```

This is the error that I am getting (article is the name of my new model that I am trying to implement)

`<class 'article.admin.MyModelAdmin'>: (admin.E002) The value of 'raw_id_fields[0]' refers to 'author', which is not an attribute of 'article.Article'.`

I am assuming it is because the post model has a author field which makes the admin look for the author field in my article model. Also not really very sure about the admin inlines, I tried to google but the concept was pretty confusing so might have made a mistake there.

**Comment by yakky** [comment]
@vivekkalyan you have to define an inline for ``MyModel``

Something like:

class MyModelAdmin(admin.TabularInlineAdmin):
    model = MyModel

class ModifiedPostAdmin(PostAdmin):
   inlines = [MyModelAdmin]

admin.site.unregister(Post)
admin.site.register(Post, ModifiedPostAdmin)

**Comment by vivekkalyan** [comment]
I was not able to get it to work, decided to just continue with my original plan of building up the blog-like features myself. Thanks for your time and help!

**Comment by yakky** [comment]
Thanks @vivekkalyan

**Comment by victor-yunenko** [comment]
Hi @yakky!

I've taken a look at this blog application and was delighted to find a solid blog platform!

My teams works on a lot of django-cms projects and of course one of the most frequent client requests is blog and events applications - which practically look identical from software point of view. But since no known to me maintained blog packages support straightforward extension I have to maintain my own bare-bones articles application. Of course I see it as quite a drawback to our community, especially since I know that I'm not the only person who's guilty of that :)

On my next cms project I intent to dedicate part of the budget for composing an extendable base for blog & events applications, and would be happy to submit it as a PR. Would you be interesting in accepting it?

**Comment by yakky** [comment]
@victor-yunenko yes, it would be interesting to understand how to implement this in a backward compatible and not confusing way
Feel free to open an issue with ideas to discuss the implementation
You might want to check the django-appdata approach to keep the model thinner and just add whatever is needed via a customized form, which would make extension much easier

**Comment by victor-yunenko** [comment]
Alright, glad to hear that, I'll let you know once I start working on it 👍
