### ISSUE TITLE
Feature-request: allow by-plugin definition of template folder

### ISSUE THREAD

**Issue by fsbraun** [nephila/djangocms-blog#295]
Currently, the template folder can be set by app hook. Already a very smart move to allow to have different blog templates and news templates.

Is it possible to override the template folder by plugin instance? My use case would be to have different ways of showing, e.g., the same post list, e.g., as using a plain list style, in columns, as a table, using a masonry style or you name it.

I would volunteer to contribute but I am a amateur coder. To my understanding this would need extension of the plugin models and the plugin classes render methods in `cms_plugin.py`.

**Comment by yakky** [comment]
Nice idea indeed. You can define a ``get_render_template`` method on the plugin class (i.e. the classes in ``cms_plugin.py``) (see http://django-cms.readthedocs.io/en/release-3.3.x/reference/plugins.html#cms.plugin_base.CMSPluginBase.get_render_template for reference) which will build the template path in same way of https://github.com/nephila/djangocms-blog/blob/develop/djangocms_blog/views.py#L51, except you will need to check ``instance.app_config``  instead of ``self.config``

**Comment by leesolway** [comment]
Would a good extension to this idea be allowing a plugin to define multiple templates along side the app config directory?

**Comment by fsbraun** [comment]
I'll give it a shot.

**Comment by yakky** [comment]
@fsbraun awesome!

**Comment by fsbraun** [comment]
Sorry, for being so high-maintenance ...

I cloned the `origin/develop` branch, added the `feature/by-plugin-templates `. Do I need privileges to push that branch back to the server? So far I seem to fail.

Next step, in my understanding, is creating a pull request from that branch. 

Thanks for helping out.

**Comment by yakky** [comment]
@fsbraun no problem in asking more info about the process.
You need to for this project to your own account, clone your own fork and push the branch with the fix to the fork. From there, you can open a pull request
As you already cloned the project, the best approach is to fork this, change the remote on your local copy (something like to ``git remote origin set-url git@github.com:fsbraun/djangocms-blog.git``)
