### ISSUE TITLE
Migration error

### ISSUE THREAD

**Issue by agajankush** [nephila/djangocms-blog#539]
I am trying to install it in my project and its giving me this error on migration:
**"djangocms_blog.0032_auto_20180109_0023"**

django.db.utils.OperationalError: (1071, 'Specified key was too long; max key length is 3072 bytes')

Can you guys suggest a solution

I tried to remove the alter migrations and force the SlugField to be 255
Then it all went through but now I am getting this error while editing the article:
**AttributeError: 'int' object has no attribute 'encode'**

**Comment by jasujm** [comment]
I have run into the same issue. With utf8mb4 encoding (the default in recent MySQL versions) the maximum key effectively limits the size of varchar fields to 767 characters. But, because slugs appear in composite indices with language codes (that add further 15 characters to the index), the actual size limit of slug alone is 752.

There is an earlier PR (https://github.com/nephila/djangocms-blog/pull/419) to address this, reducing the slug length to 767, but that doesn't cut it for newer versions. I use my own fork of djangocms-blog for own project using utf8mb4, and there simply substituting 752 for max lengths in both models and migrations was enough to solve the issue.

I submitted a pull request (https://github.com/nephila/djangocms-blog/pull/540). Feel free to merge or modify it. It may be overkill because I shorten other fields too for consistency.

**Comment by yakky** [comment]
Fixed in #540
Will be released in version 1.1 due soon
