### ISSUE TITLE
Is djangocms-blog alive?

### ISSUE THREAD

**Issue by febsn** [nephila/djangocms-blog#698]
Since there hasn't been a release for more than a year, I'm wondering if djangocms-blog is still being maintained. @yakky would you mind sharing on the project's future?

**Comment by petrklus** [comment]
Curious as well!

**Comment by tacc-wbomar** [comment]
The new [djangocms-frontend](https://github.com/fsbraun/djangocms-frontend) plugin, which [will be endorsed by the Django CMS Association](https://github.com/fsbraun/djangocms-frontend/issues/8), has [prominent mention of djangocms-blog as a compatible app](https://github.com/fsbraun/djangocms-frontend#key-features).

**Comment by yakky** [comment]
@febsn @petrklus @wesleyboar thanks a lot for the interest in djangocms-blog. Even if it's been dormant due to personal reasons, lately, our plan is to get it back on track and align it with the rest of the django CMS ecosystem.

We plan to make the testsuite work again in the next days to be able to officially support current django and django CMS release

Thanks again for your interest and patience

**Comment by febsn** [comment]
@yakky that's great news, thank you very much!
