### ISSUE TITLE
u'djangocms_blog' is not a registered namespace

### ISSUE THREAD

**Issue by Zundrium** [nephila/djangocms-blog#75]
When I added a plugin to my page, this showed up.
I fixed it by adding `url(r'^blog/', include('djangocms_blog.urls', namespace='djangocms_blog')),` to the urls.py. If this is the normal way to fix it. Please add it to the installation docs.

**Comment by motleytech** [comment]
I saw a similar error while creating my own djangocms-blog setup.

The problem in that case was that I needed to restart the django server after associating a page with the blog app (apparently because of caching).

Could this be related?

**Comment by Zundrium** [comment]
Sadly it still happens for me even if I restart it twice without the url() in the urls.py.

**Comment by motleytech** [comment]
It seems like a bug.
I hope the repo maintainers can comment on this.

**Comment by yakky** [comment]
djangocms-blog is namespace-enabled thus it requires a application name to be defined when loaded into the urlconf. Normally this is done by using apphooks as documented in the readme, which will ask for the application name into the page advanced settings.
As per django-cms documentation, loading an apphooks requires a server restart because of the way django handles urlconfs.

If this two topics are not clear enough in the current documentation, we'll try to improve it.
Thanks for reporting

**Comment by yakky** [comment]
Closing as this has been cleared in the documentation

**Comment by Dean-Christian-Armada** [comment]
Guys, I would suggest to do an example of apphook configuration in documentation especially for the very newbies

**Comment by yakky** [comment]
@Dean-Christian-Armada opened as #458
